POST {{baseUrl}}/transactions/import HTTP/1.1
Content-Type: multipart/form-data; boundary=myboundaryname
Authorization: Bearer {{token}}

--myboundaryname
Content-Disposition: form-data; name="file"; filename="file.csv"
Content-Type: text/csv

< ./file.csv
--myboundaryname--

# References:
# -> Envia requisicao pelo insomnia e checa formato na aba timeline
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# https://stackoverflow.com/questions/61473990/how-to-post-an-image-with-form-data-in-rest-client-for-vscode
# https://stackoverflow.com/questions/3508338/what-is-the-boundary-in-multipart-form-data

